<a href="https://colab.research.google.com/github/Jyothsna9618/Jabboju1/blob/main/Assignment_05/Assignment_05_part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part-4 : Introduction to Numpy

In [73]:
import sys
import numpy as np
import warnings

#Basic Numpy Arrays

In [74]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [75]:
a = np.array([1, 2, 3, 4])


In [76]:
b = np.array([0, .5, 1, 1.5, 2])


In [77]:
a[0], a[1]

(1, 2)

In [78]:
a[0:]

array([1, 2, 3, 4])

In [79]:
a[1:3]

array([2, 3])

In [80]:
a[1:-1]


array([2, 3])

In [81]:
a[::2]


array([1, 3])

In [82]:
a[1::1]

array([2, 3, 4])

In [83]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [84]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [85]:
b[[0, 2, -1]]

array([0., 1., 2.])

#Array Types

In [86]:
a

array([1, 2, 3, 4])

In [87]:
a.dtype

dtype('int64')

In [88]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [89]:
b.dtype

dtype('float64')

In [90]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [91]:
np.array([1, 2, 3, 4], dtype=np.int8)


array([1, 2, 3, 4], dtype=int8)

In [92]:
c = np.array(['a', 'b', 'c'])

In [93]:
c.dtype

dtype('<U1')

In [94]:
d = np.array([{'a': 1}, sys])


In [95]:
d.dtype

dtype('O')

#Dimesnsions and shapes

In [96]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [97]:
A.shape

(2, 3)

In [98]:
A.ndim

2

In [99]:
A.size

6

In [100]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [101]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [102]:
B.shape


(2, 2, 3)

In [103]:
B.ndim

3

In [104]:
B.size

12

In [105]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [106]:
C.dtype

dtype('O')

In [107]:
C.dtype

dtype('O')

In [108]:
C.size

2

In [109]:
type(C[0])

list

#Indexing and Slicing of Matrices

In [110]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [111]:
A[1]

array([4, 5, 6])

In [112]:
A[1][0]

4

In [113]:
# A[d1, d2, d3, d4]

In [114]:
A[1, 0]

4

In [115]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
A[:, :2]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [117]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [118]:
A[:2, 2:]

array([[3],
       [6]])

In [119]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
A[1] = np.array([10, 10, 10])

In [121]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [122]:
A[2] = 99

In [123]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#Summary statistics:

In [124]:
a = np.array([1, 2, 3, 4])

In [125]:
a.sum()

10

In [126]:
a.mean()

2.5

In [127]:
a.std()

1.118033988749895

In [128]:
a.var()

1.25

In [129]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [130]:
A.sum()

45

In [131]:
A.mean()

5.0

In [132]:
A.std()

2.581988897471611

In [133]:
A.sum(axis=0)

array([12, 15, 18])

In [134]:
A.sum(axis=1)

array([ 6, 15, 24])

In [135]:
A.mean(axis=0)

array([4., 5., 6.])

In [136]:
A.mean(axis=1)

array([2., 5., 8.])

In [137]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [138]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

#Broadcasting and Vectorized operations:

In [139]:
a = np.arange(4)

In [140]:
a

array([0, 1, 2, 3])

In [141]:
a + 10

array([10, 11, 12, 13])

In [142]:
a * 10

array([ 0, 10, 20, 30])

In [143]:
a

array([0, 1, 2, 3])

In [144]:
a += 100

In [145]:
a

array([100, 101, 102, 103])

In [146]:
l = [0, 1, 2, 3]

In [147]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [148]:
a = np.arange(4)


In [149]:
a

array([0, 1, 2, 3])

In [150]:
b = np.array([10, 10, 10, 10])

In [151]:
b

array([10, 10, 10, 10])

In [152]:
a + b

array([10, 11, 12, 13])

In [153]:
a * b

array([ 0, 10, 20, 30])

#Boolean arrays:

In [154]:
a = np.arange(4)

In [155]:
a

array([0, 1, 2, 3])

In [156]:
a[0], a[-1]


(0, 3)

In [157]:
a[[0, -1]]


array([0, 3])

In [158]:
a[[True, False, False, True]]

array([0, 3])

In [159]:
a

array([0, 1, 2, 3])

In [160]:
a >= 2

array([False, False,  True,  True])

In [161]:
a[a >= 2]

array([2, 3])

In [162]:
a.mean()

1.5

In [163]:
a[a > a.mean()]

array([2, 3])

In [164]:
a[~(a > a.mean())]


array([0, 1])

In [165]:
a[(a == 0) | (a == 1)]


array([0, 1])

In [166]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [167]:
A = np.random.randint(100, size=(3, 3))

In [168]:
A

array([[84,  1, 41],
       [82, 73, 63],
       [87, 45,  2]])

In [169]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([84, 41, 73, 87,  2])

In [170]:
A > 30

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [171]:
A[A > 30]


array([84, 41, 82, 73, 63, 87, 45])

#Linear Algebra:

In [172]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [173]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [174]:
A.dot(B)


array([[20, 14],
       [56, 41],
       [92, 68]])

In [175]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [176]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [177]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [178]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

#Size of objects in Memory:

 ## Int, floats

In [179]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [180]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [181]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [182]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [183]:
np.dtype(float).itemsize

8

# Lists are even larger:

In [184]:
# A one-element list
sys.getsizeof([1])

80

In [185]:
# An array of one element in numpy
np.array([1]).nbytes

8

#And performance is also important:

In [186]:
l = list(range(100000))

In [187]:
a = np.arange(100000)

In [188]:
%time np.sum(a ** 2)

CPU times: user 1.14 ms, sys: 28 µs, total: 1.17 ms
Wall time: 1.86 ms


333328333350000

In [189]:
%time sum([x ** 2 for x in l])

CPU times: user 82.6 ms, sys: 9.71 ms, total: 92.3 ms
Wall time: 102 ms


333328333350000

#Useful Numpy functions:

##random

In [190]:
np.random.random(size=2)

array([0.69493264, 0.76064826])

In [191]:
np.random.normal(size=2)


array([1.56139065, 0.65557057])

In [192]:
np.random.rand(2, 4)

array([[0.95190067, 0.19920334, 0.16791428, 0.64268844],
       [0.2098426 , 0.60600907, 0.39970875, 0.48911891]])

#arrange:

In [193]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [195]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#reshape:

In [196]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [197]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#Linespace:

In [198]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [199]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [200]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

# zeros, ones, empty

In [201]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [202]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [203]:
np.zeros((3, 3), dtype=np.int)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [204]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [205]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [206]:
np.empty(5)


array([1., 1., 1., 1., 1.])

In [207]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

#Identity and eye:

In [208]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [209]:
np.eye(3, 3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [210]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [211]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [212]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [217]:
"Hello World"[6]


'W'